#!/usr/bin/env node
// front/scripts/gen-version.mjs
// Generates front/src/lib/version.ts from the repo-wide version source of truth.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { versionInfo } from '../../scripts/version.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'src', 'lib', 'version.ts');

const info = versionInfo();
mkdirSync(dirname(out), { recursive: true });

const banner = '// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n';
const body = `export interface VersionInfo {
  version: string;
  env: 'production' | 'development';
  gitSha: string;
  buildTime: string;
}

export const VERSION: VersionInfo = ${JSON.stringify(info, null, 2)} as const;
`;

writeFileSync(out, banner + body);
console.log(`[gen-version] wrote ${out} → ${info.version} (${info.env})`);
