#!/usr/bin/env node
// scripts/gen-version.mjs — unified version file generator
//
// Usage:
//   node scripts/gen-version.mjs backend   → writes backend/src/_generated/version.json
//   node scripts/gen-version.mjs front     → writes front/src/lib/version.ts
//
// Called from package.json prebuild/pretest scripts and docker:dev / docker:reset.
// The script resolves paths relative to the repo root regardless of the calling directory.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { versionInfo } from './version.mjs';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = process.argv[2];

if (!['backend', 'front', 'docs', 'all'].includes(target)) {
  console.error('Usage: node scripts/gen-version.mjs <backend|front|docs|all>');
  process.exit(1);
}

const info = versionInfo();

function writeBackend() {
  const out = resolve(repoRoot, 'backend', 'src', '_generated', 'version.json');
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, JSON.stringify(info, null, 2) + '\n');
  console.log(`[gen-version] wrote ${out} → ${info.version} (${info.env})`);
}

function writeFrontOrDocs(t) {
  const outPath = t === 'front'
    ? resolve(repoRoot, 'front', 'src', 'lib', 'version.ts')
    : resolve(repoRoot, 'docs', 'src', 'lib', 'version.ts');
  mkdirSync(dirname(outPath), { recursive: true });
  const banner =
    '// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n';
  const body = `export interface VersionInfo {
  version: string;
  env: 'production' | 'development';
  gitSha: string;
  buildTime: string;
}

export const VERSION: VersionInfo = ${JSON.stringify(info, null, 2)} as const;
`;
  writeFileSync(outPath, banner + body);
  console.log(`[gen-version] wrote ${outPath} → ${info.version} (${info.env})`);
}

if (target === 'all') {
  writeBackend();
  writeFrontOrDocs('front');
  writeFrontOrDocs('docs');
} else if (target === 'backend') {
  writeBackend();
} else {
  writeFrontOrDocs(target);
}
